---
abstract: 'File store for MojoX::Session'
author:
  - 'Алексей Суриков <ksuri@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MojoX::Session::Store::File
name: MojoX-Session-Store-File
no_index:
  directory:
    - inc
    - t
requires:
  File::Spec: 0
  FreezeThaw: 0
  Mojo: 0.999914
  MojoX::Session: 0.15
  Storable: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
